[package]
name = "intentrace"
version = "0.5.0"
description = "intentrace is strace with intent, it goes all the way for you instead of half the way."
edition = "2021"
license = "MIT"
repository = "https://github.com/sectordistrict/intentrace"

[dependencies]
clone3 = "0.2.3"
colored = "2.1.0"
ctrlc = { version = "3.4.5", features = ["termination"] }
errno = "0.3.9"
exec = "0.3.1"
lazy_static = "1.5.0"
nix = { version = "0.29.0", features = ["aio", "event", "fs", "mman", "net", "process", "ptrace", "resource", "signal", "uio"] }
num_cpus = "1.16.0"
page_size = "0.6.0"
pete = { version = "0.12.0"}
procfs = "0.16.0"
rustix = { version = "0.38.35", features = ["mm", "net", "rand"] }
syscalls = "0.6.18"
tabled = "0.16.0"
termbg = "0.6.1"
uzers = "0.12.1"

# [profile.release]
# lto = true
